version: '3'
services:
  zookeeper:
    image: zookeeper:3.4.12
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:1.1.0
    container_name: kafka
    hostname: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_DELETE_TOPIC_ENABLE: "true"
    depends_on:
     - zookeeper
